#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("passphrase.Resource", IsApplication=true)]

namespace passphrase
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int passwordTranslateOptions = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int chooseTextView = 2131165189;
			
			// aapt resource value: 0x7f07000c
			public const int closeApp = 2131165196;
			
			// aapt resource value: 0x7f070007
			public const int editTextIn = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int entropySizeTextField = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int generateEntropyButton = 2131165185;
			
			// aapt resource value: 0x7f07000a
			public const int generateFromEntropy = 2131165194;
			
			// aapt resource value: 0x7f070004
			public const int infoTextView = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int outputTextView = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int textView1 = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int translateButton = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int translateSpinner = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int translatedtextView = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int translator = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GenerateEntropy = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PasswordTlanslator = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int app_name = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int buttonGenerateOnEntropy = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int exit = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int genFromEntropy = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int mainInfo = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int passwordTranslateOption = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int translate = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int translator = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int welcomeText = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
